### ISSUE TITLE
Trowing error: Unsupported language code with custom languages and url placeholders

### ISSUE THREAD

**Issue by saaaab1213** [crowdin/ota-client-js#13]
`crowdin.yml` source file require to have `Translation` value and it requires a placeholder.
When working with custom languages as language info is stored locally in src/internal/util/exportPattern.ts it is not able to find any language that matches the one needed for building the route and throws Unsupported language code error

`crowdin.yml`:
```

"project_id_env" : "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  "source" : "/src/translations/screens.json",
  "dest" : "/screens.json",
  "translation" : "/%locale%/screens.json",
  "update_option": "update_as_unapproved",
 },
  {"source" : "/src/translations/general.json",
    "dest" : "/general.json",
    "translation" : "/%locale%/general.json",
    "update_option": "update_as_unapproved"
  }
]`
```

`manifest.json`
````
{"files":["\/%locale%\/general.json","\/%locale%\/screens.json"],
"languages":["ca","en","it","en-ls","es-ls","es-ES"],
"language_mapping":[],
"timestamp":1619601797}
````

"en-ls","es-ls" languages both throws that error

Is there any possibility of retrieving custom languages info to avoid custom patches and workarounds?

**Comment by yevheniyJ** [comment]
@saaaab1213 fixed in v0.3.0
