### ISSUE TITLE
Some translations are missing from my project

### ISSUE THREAD

**Issue by liantianyun** [crowdin/ota-client-js#8]
Hi, I used React -native- SDK before and I ran into a bug that I couldn't get the Indonesian and Hebrew translations.
https://github.com/crowdin/react-native-sdk/issues/15
So I tried to use this library, when I called client.listlanguages (), I got the result is:
```
["af", "sq", "ar", "bn", "bg", "ca", "zh-CN", "zh-TW", "hr", "cs", "da", "nl", "et", "fi", "fr", "de", "el", "he", "hu", "id", "it", "ja", "km", "ko", "lv", "lt", "mk", "ms", "fa", "pl", "pt-PT", "pt-BR", "ro", "ru", "sr", "sk", "sl", "es-ES", "es-EM", "sv-SE", "th", "tr", "uk", "ur-PK", "vi"]
```
 the list without these two languages('id' and 'he') was in it, I think this is the reason why I couldn't get it through React -native- SDK before, please help me locate why they don't exist, they do exist in crowdin project.
![image](https://user-images.githubusercontent.com/45311559/103723046-22e20700-500c-11eb-93ae-c95cc86fd27b.png)

**Comment by andrii-bodnar** [comment]
Hi @liantianyun!

In the provided result Hebrew (he) and Indonesian (id) languages are available.

![screenshot-github com-2021 01 06-10_22_36](https://user-images.githubusercontent.com/29282228/103746068-27f18700-5009-11eb-8327-8ef33dd65f8d.png)

**Comment by liantianyun** [comment]
> Hi @liantianyun!
> 
> In the provided result Hebrew (he) and Indonesian (id) languages are available.
> 
> ![screenshot-github com-2021 01 06-10_22_36](https://user-images.githubusercontent.com/29282228/103746068-27f18700-5009-11eb-8327-8ef33dd65f8d.png)

I'm sorry, that's just my vision. I'll try again

**Comment by liantianyun** [comment]
Thank you. My problem has been solved

**Comment by andrii-bodnar** [comment]
Hi @liantianyun!

Could you please tell which library you are using now and if everything is ok now?

**Comment by liantianyun** [comment]
> Hi @liantianyun!
> 
> Could you please tell which library you are using now and if everything is ok now?
Yes, everything is normal now. If there is any problem, I will communicate with you

**Comment by liantianyun** [comment]
> Hi @liantianyun!
> 
> Could you please tell which library you are using now and if everything is ok now?

Yes, everything is normal now. If there is any problem, I will communicate with you
